name = "portfolio-ecom"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@1"
cwd = "."

[env.production]
compatibility_flags = ["nodejs_compat"]
