name = "portfolio-ecom"
compatibility_date = "2024-01-01"

# Build configuration for static export
[build]
command = "npm run build"
cwd = "."

[build.output_dir] = "out"

# Output directory for static export
# Static site configuration
[pages]
# No compatibility flags needed for static sites
